FROM node:alpine as compile-one
ENV NODE_OPTIONS=--openssl-legacy-provider
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx as compile-two
COPY --from=0 /app/build /usr/share/nginx/html