name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-push-image-one:
    name: compile-one
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: buildx
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push compile-one
        id: docker_build_one
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.zad2
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          target: compile-one
          push: true
          tags: flossyy/tester:tagname-one
          cache-from: type=registry,ref=flossyy/tester:tagname-one
          cache-to: type=inline


  build-push-image-two:
    name: compile-one
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: buildx
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push compile-two
        id: docker_build_two
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.zad2
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          target: compile-two
          push: true
          tags: flossyy/tester:tagname-two
          cache-from: type=registry,ref=flossyy/tester:tagname-two
          cache-to: type=inline
